apiVersion: v1
kind: Service
metadata:
    name: my-clusterip
spec: 
    type: ClusterIP 
    selector:
       app: nginx
    ports:
    - name: http
      port: 30002
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: harshajain/ip_app:2
        imagePullPolicy: Always
        ports:
        - containerPort: 80